/* ---------- headers */

#include "xdk\xgraphicsd\compiledprogram.h"

/* ---------- constants */

/* ---------- definitions */

/* ---------- prototypes */

/* ---------- globals */

/* ---------- public code */

/* ---------- private code */

/* ---------- reverse engineering */

// unsigned int XGRAPHICS::CP_IsExecutable(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_Destroy(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// void XGRAPHICS::CP_AddRef(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// enum XGRAPHICS::_E_COMPILED_PROGRAM_TYPE XGRAPHICS::CP_GetType(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// void * XGRAPHICS::CP_CreateDataObject(struct XGRAPHICS::_SSM_SSMDEVICE2CLIENT_INTERFACE *);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_DestroyDataObject(void *);
// void XGRAPHICS::CP_MakeReadOnly(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// struct XGRAPHICS::_CP_SHADERPROGRAM_BLOCK * XGRAPHICS::CP_GetPS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// struct XGRAPHICS::_CP_SHADERPROGRAM_BLOCK * XGRAPHICS::CP_GetVS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// struct XGRAPHICS::_CS_COMPILED_SHADER * XGRAPHICS::CP_GetCS_ps(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// struct XGRAPHICS::_CS_COMPILED_SHADER * XGRAPHICS::CP_GetCS_vs(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// struct XGRAPHICS::_CP_RENDERSTATE_BLOCK * XGRAPHICS::CP_GetRS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, unsigned int);
// enum XGRAPHICS::_VERTEX_INSTR_DESTSEL XGRAPHICS::ConvertVertexFetchInstrMask(char);
// void XGRAPHICS::ProcessVertexInputPatch(struct XGRAPHICS::_CS_VERTEX_INPUT_PATCH *, struct XGRAPHICS::_CP_SHADERPROGRAM_BLOCK *, struct XGRAPHICS::_ABSTRACT_STATE *, struct XGRAPHICS::_SSM_REGISTRY *);
// struct XGRAPHICS::_CP_SHADERPROGRAM_BLOCK * XGRAPHICS::PatchCompiledShader(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, struct XGRAPHICS::_CS_COMPILED_SHADER *, struct XGRAPHICS::_ABSTRACT_STATE *);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocFetchConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, enum XGRAPHICS::E_FETCH_TYPE, unsigned int, unsigned int *, unsigned int *);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocStaticScalarConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, enum XGRAPHICS::E_IA_FLOAT_CHANNEL, float);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocQueryScalarConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, enum XGRAPHICS::E_IA_FLOAT_CHANNEL, enum XGRAPHICS::E_SSM_COMPILEGET_QUERY, int);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocExportConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, unsigned int);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocQueryBoolConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, enum XGRAPHICS::E_SSM_COMPILEWITH_QUERY, unsigned int);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_CopyPixelShader(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, unsigned int, void *);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_CopyVertexShader(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, unsigned int, void *);
// void XGRAPHICS::CP_SetRS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::_E_R400_STATE, unsigned int);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_SetInterpUsage(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, enum XGRAPHICS::_E_INTERP_USAGE, unsigned int, union XGRAPHICS::_CS_COMPONENT_SEL, enum XGRAPHICS::_E_INTERP_SAMPLING, int, int *, int *, int *);
// struct XGRAPHICS::_CP_COMPILED_PROGRAM * XGRAPHICS::CP_Create(void *, void * (*)(void *, unsigned int), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, void *), struct XGRAPHICS::_TS_TEXTURE_SERVER *, struct XGRAPHICS::_SSM_REGISTRY *, struct XGRAPHICS::_ORDERED_LIST_FACTORY *, struct XGRAPHICS::_INTEGER_LIST_FACTORY *, struct XGRAPHICS::_OBJECT_LIST_FACTORY *, enum XGRAPHICS::_E_COMPILED_PROGRAM_TYPE);
// void XGRAPHICS::ProcessCompilerStates(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, struct XGRAPHICS::_OBJECT_LIST *);
// void XGRAPHICS::CP_ReplacePS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, struct XGRAPHICS::_CS_COMPILED_SHADER *, struct XGRAPHICS::_ABSTRACT_STATE *);
// void XGRAPHICS::CP_ReplaceVS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, struct XGRAPHICS::_CS_COMPILED_SHADER *, struct XGRAPHICS::_ABSTRACT_STATE *);
// void XGRAPHICS::CP_UpdatePSCompilerState(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// void XGRAPHICS::CP_UpdateVSCompilerState(struct XGRAPHICS::_CP_COMPILED_PROGRAM *);

//unsigned int XGRAPHICS::CP_IsExecutable(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_IsExecutable@XGRAPHICS@@YAIPAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_Destroy(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_Destroy@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//void XGRAPHICS::CP_AddRef(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_AddRef@XGRAPHICS@@YAXPAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//enum XGRAPHICS::_E_COMPILED_PROGRAM_TYPE XGRAPHICS::CP_GetType(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_GetType@XGRAPHICS@@YA?AW4_E_COMPILED_PROGRAM_TYPE@1@PAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//void * XGRAPHICS::CP_CreateDataObject(struct XGRAPHICS::_SSM_SSMDEVICE2CLIENT_INTERFACE *)
//{
//    mangled_ppc("?CP_CreateDataObject@XGRAPHICS@@YAPAXPAU_SSM_SSMDEVICE2CLIENT_INTERFACE@1@@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_DestroyDataObject(void *)
//{
//    mangled_ppc("?CP_DestroyDataObject@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAX@Z");
//};

//void XGRAPHICS::CP_MakeReadOnly(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_MakeReadOnly@XGRAPHICS@@YAXPAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//struct XGRAPHICS::_CP_SHADERPROGRAM_BLOCK * XGRAPHICS::CP_GetPS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_GetPS@XGRAPHICS@@YAPAU_CP_SHADERPROGRAM_BLOCK@1@PAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//struct XGRAPHICS::_CP_SHADERPROGRAM_BLOCK * XGRAPHICS::CP_GetVS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_GetVS@XGRAPHICS@@YAPAU_CP_SHADERPROGRAM_BLOCK@1@PAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//struct XGRAPHICS::_CS_COMPILED_SHADER * XGRAPHICS::CP_GetCS_ps(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_GetCS_ps@XGRAPHICS@@YAPAU_CS_COMPILED_SHADER@1@PAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//struct XGRAPHICS::_CS_COMPILED_SHADER * XGRAPHICS::CP_GetCS_vs(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_GetCS_vs@XGRAPHICS@@YAPAU_CS_COMPILED_SHADER@1@PAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//struct XGRAPHICS::_CP_RENDERSTATE_BLOCK * XGRAPHICS::CP_GetRS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, unsigned int)
//{
//    mangled_ppc("?CP_GetRS@XGRAPHICS@@YAPAU_CP_RENDERSTATE_BLOCK@1@PAU_CP_COMPILED_PROGRAM@1@I@Z");
//};

//enum XGRAPHICS::_VERTEX_INSTR_DESTSEL XGRAPHICS::ConvertVertexFetchInstrMask(char)
//{
//    mangled_ppc("?ConvertVertexFetchInstrMask@XGRAPHICS@@YA?AW4_VERTEX_INSTR_DESTSEL@1@D@Z");
//};

//void XGRAPHICS::ProcessVertexInputPatch(struct XGRAPHICS::_CS_VERTEX_INPUT_PATCH *, struct XGRAPHICS::_CP_SHADERPROGRAM_BLOCK *, struct XGRAPHICS::_ABSTRACT_STATE *, struct XGRAPHICS::_SSM_REGISTRY *)
//{
//    mangled_ppc("?ProcessVertexInputPatch@XGRAPHICS@@YAXPAU_CS_VERTEX_INPUT_PATCH@1@PAU_CP_SHADERPROGRAM_BLOCK@1@PAU_ABSTRACT_STATE@1@PAU_SSM_REGISTRY@1@@Z");
//};

//struct XGRAPHICS::_CP_SHADERPROGRAM_BLOCK * XGRAPHICS::PatchCompiledShader(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, struct XGRAPHICS::_CS_COMPILED_SHADER *, struct XGRAPHICS::_ABSTRACT_STATE *)
//{
//    mangled_ppc("?PatchCompiledShader@XGRAPHICS@@YAPAU_CP_SHADERPROGRAM_BLOCK@1@PAU_CP_COMPILED_PROGRAM@1@PAU_CS_COMPILED_SHADER@1@PAU_ABSTRACT_STATE@1@@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocFetchConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, enum XGRAPHICS::E_FETCH_TYPE, unsigned int, unsigned int *, unsigned int *)
//{
//    mangled_ppc("?CP_AllocFetchConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@W4IL_Shader_Type@1@W4E_FETCH_TYPE@1@IPAI3@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocStaticScalarConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, enum XGRAPHICS::E_IA_FLOAT_CHANNEL, float)
//{
//    mangled_ppc("?CP_AllocStaticScalarConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@W4IL_Shader_Type@1@IW4E_IA_FLOAT_CHANNEL@1@M@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocQueryScalarConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, enum XGRAPHICS::E_IA_FLOAT_CHANNEL, enum XGRAPHICS::E_SSM_COMPILEGET_QUERY, int)
//{
//    mangled_ppc("?CP_AllocQueryScalarConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@W4IL_Shader_Type@1@IW4E_IA_FLOAT_CHANNEL@1@W4E_SSM_COMPILEGET_QUERY@1@H@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocExportConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, unsigned int)
//{
//    mangled_ppc("?CP_AllocExportConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@W4IL_Shader_Type@1@II@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_AllocQueryBoolConst(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, enum XGRAPHICS::E_SSM_COMPILEWITH_QUERY, unsigned int)
//{
//    mangled_ppc("?CP_AllocQueryBoolConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@W4IL_Shader_Type@1@IW4E_SSM_COMPILEWITH_QUERY@1@I@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_CopyPixelShader(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, unsigned int, void *)
//{
//    mangled_ppc("?CP_CopyPixelShader@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@IPAX@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_CopyVertexShader(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, unsigned int, void *)
//{
//    mangled_ppc("?CP_CopyVertexShader@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@IPAX@Z");
//};

//void XGRAPHICS::CP_SetRS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::_E_R400_STATE, unsigned int)
//{
//    mangled_ppc("?CP_SetRS@XGRAPHICS@@YAXPAU_CP_COMPILED_PROGRAM@1@W4_E_R400_STATE@1@I@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::CP_SetInterpUsage(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, enum XGRAPHICS::IL_Shader_Type, unsigned int, enum XGRAPHICS::_E_INTERP_USAGE, unsigned int, union XGRAPHICS::_CS_COMPONENT_SEL, enum XGRAPHICS::_E_INTERP_SAMPLING, int, int *, int *, int *)
//{
//    mangled_ppc("?CP_SetInterpUsage@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_CP_COMPILED_PROGRAM@1@W4IL_Shader_Type@1@IW4_E_INTERP_USAGE@1@IT_CS_COMPONENT_SEL@1@W4_E_INTERP_SAMPLING@1@HPAH55@Z");
//};

//struct XGRAPHICS::_CP_COMPILED_PROGRAM * XGRAPHICS::CP_Create(void *, void * (*)(void *, unsigned int), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, void *), struct XGRAPHICS::_TS_TEXTURE_SERVER *, struct XGRAPHICS::_SSM_REGISTRY *, struct XGRAPHICS::_ORDERED_LIST_FACTORY *, struct XGRAPHICS::_INTEGER_LIST_FACTORY *, struct XGRAPHICS::_OBJECT_LIST_FACTORY *, enum XGRAPHICS::_E_COMPILED_PROGRAM_TYPE)
//{
//    mangled_ppc("?CP_Create@XGRAPHICS@@YAPAU_CP_COMPILED_PROGRAM@1@PAXP6APAX0I@ZP6A?AW4_E_SSM_RETURNCODE@1@00@ZPAU_TS_TEXTURE_SERVER@1@PAU_SSM_REGISTRY@1@PAU_ORDERED_LIST_FACTORY@1@PAU_INTEGER_LIST_FACTORY@1@PAU_OBJECT_LIST_FACTORY@1@W4_E_COMPILED_PROGRAM_TYPE@1@@Z");
//};

//void XGRAPHICS::ProcessCompilerStates(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, struct XGRAPHICS::_OBJECT_LIST *)
//{
//    mangled_ppc("?ProcessCompilerStates@XGRAPHICS@@YAXPAU_CP_COMPILED_PROGRAM@1@PAU_OBJECT_LIST@1@@Z");
//};

//void XGRAPHICS::CP_ReplacePS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, struct XGRAPHICS::_CS_COMPILED_SHADER *, struct XGRAPHICS::_ABSTRACT_STATE *)
//{
//    mangled_ppc("?CP_ReplacePS@XGRAPHICS@@YAXPAU_CP_COMPILED_PROGRAM@1@PAU_CS_COMPILED_SHADER@1@PAU_ABSTRACT_STATE@1@@Z");
//};

//void XGRAPHICS::CP_ReplaceVS(struct XGRAPHICS::_CP_COMPILED_PROGRAM *, struct XGRAPHICS::_CS_COMPILED_SHADER *, struct XGRAPHICS::_ABSTRACT_STATE *)
//{
//    mangled_ppc("?CP_ReplaceVS@XGRAPHICS@@YAXPAU_CP_COMPILED_PROGRAM@1@PAU_CS_COMPILED_SHADER@1@PAU_ABSTRACT_STATE@1@@Z");
//};

//void XGRAPHICS::CP_UpdatePSCompilerState(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_UpdatePSCompilerState@XGRAPHICS@@YAXPAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//void XGRAPHICS::CP_UpdateVSCompilerState(struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?CP_UpdateVSCompilerState@XGRAPHICS@@YAXPAU_CP_COMPILED_PROGRAM@1@@Z");
//};

