/* ---------- headers */


/* ---------- constants */

/* ---------- definitions */

/* ---------- prototypes */

/* ---------- globals */

/* ---------- public code */

/* ---------- private code */

/* ---------- reverse engineering */

// struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR * XGRAPHICS::IA_Create(void *, void * (*)(void *, unsigned int), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, void *), struct XGRAPHICS::_SSM_REGISTRY *);
// void XGRAPHICS::IA_Destroy(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *);
// void XGRAPHICS::IA_Init(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_AllocStaticScalarConst(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, unsigned int, enum XGRAPHICS::E_IA_FLOAT_CHANNEL, float);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_AllocQueryScalarConst(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, unsigned int, enum XGRAPHICS::E_IA_FLOAT_CHANNEL, enum XGRAPHICS::E_SSM_COMPILEGET_QUERY, int);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_AllocExportConst(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, unsigned int, unsigned int);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_AllocQueryBoolConst(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, unsigned int, enum XGRAPHICS::E_SSM_COMPILEWITH_QUERY, unsigned int);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_CreatePackedBlock(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, struct XGRAPHICS::_IA_INTERNALCONST_BLOCK_HEADER **);
// void XGRAPHICS::IA_DestroyPackedBlock(struct XGRAPHICS::_IA_INTERNALCONST_BLOCK_HEADER *);
// unsigned int XGRAPHICS::IA_GetFloatUsageBlock(struct XGRAPHICS::_IA_INTERNALCONST_BLOCK_HEADER *, struct XGRAPHICS::_IA_FLOATUSAGE_BLOCK **);
// unsigned int XGRAPHICS::IA_GetBoolUsageBlock(struct XGRAPHICS::_IA_INTERNALCONST_BLOCK_HEADER *, struct XGRAPHICS::_IA_BOOLUSAGE_BLOCK **);

//struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR * XGRAPHICS::IA_Create(void *, void * (*)(void *, unsigned int), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, void *), struct XGRAPHICS::_SSM_REGISTRY *)
//{
//    mangled_ppc("?IA_Create@XGRAPHICS@@YAPAU_IA_INTERNALCONST_ALLOCATOR@1@PAXP6APAX0I@ZP6A?AW4_E_SSM_RETURNCODE@1@00@ZPAU_SSM_REGISTRY@1@@Z");
//};

//void XGRAPHICS::IA_Destroy(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *)
//{
//    mangled_ppc("?IA_Destroy@XGRAPHICS@@YAXPAU_IA_INTERNALCONST_ALLOCATOR@1@@Z");
//};

//void XGRAPHICS::IA_Init(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *)
//{
//    mangled_ppc("?IA_Init@XGRAPHICS@@YAXPAU_IA_INTERNALCONST_ALLOCATOR@1@@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_AllocStaticScalarConst(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, unsigned int, enum XGRAPHICS::E_IA_FLOAT_CHANNEL, float)
//{
//    mangled_ppc("?IA_AllocStaticScalarConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_IA_INTERNALCONST_ALLOCATOR@1@IW4E_IA_FLOAT_CHANNEL@1@M@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_AllocQueryScalarConst(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, unsigned int, enum XGRAPHICS::E_IA_FLOAT_CHANNEL, enum XGRAPHICS::E_SSM_COMPILEGET_QUERY, int)
//{
//    mangled_ppc("?IA_AllocQueryScalarConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_IA_INTERNALCONST_ALLOCATOR@1@IW4E_IA_FLOAT_CHANNEL@1@W4E_SSM_COMPILEGET_QUERY@1@H@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_AllocExportConst(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, unsigned int, unsigned int)
//{
//    mangled_ppc("?IA_AllocExportConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_IA_INTERNALCONST_ALLOCATOR@1@II@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_AllocQueryBoolConst(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, unsigned int, enum XGRAPHICS::E_SSM_COMPILEWITH_QUERY, unsigned int)
//{
//    mangled_ppc("?IA_AllocQueryBoolConst@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_IA_INTERNALCONST_ALLOCATOR@1@IW4E_SSM_COMPILEWITH_QUERY@1@I@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::IA_CreatePackedBlock(struct XGRAPHICS::_IA_INTERNALCONST_ALLOCATOR *, struct XGRAPHICS::_IA_INTERNALCONST_BLOCK_HEADER **)
//{
//    mangled_ppc("?IA_CreatePackedBlock@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_IA_INTERNALCONST_ALLOCATOR@1@PAPAU_IA_INTERNALCONST_BLOCK_HEADER@1@@Z");
//};

//void XGRAPHICS::IA_DestroyPackedBlock(struct XGRAPHICS::_IA_INTERNALCONST_BLOCK_HEADER *)
//{
//    mangled_ppc("?IA_DestroyPackedBlock@XGRAPHICS@@YAXPAU_IA_INTERNALCONST_BLOCK_HEADER@1@@Z");
//};

//unsigned int XGRAPHICS::IA_GetFloatUsageBlock(struct XGRAPHICS::_IA_INTERNALCONST_BLOCK_HEADER *, struct XGRAPHICS::_IA_FLOATUSAGE_BLOCK **)
//{
//    mangled_ppc("?IA_GetFloatUsageBlock@XGRAPHICS@@YAIPAU_IA_INTERNALCONST_BLOCK_HEADER@1@PAPAU_IA_FLOATUSAGE_BLOCK@1@@Z");
//};

//unsigned int XGRAPHICS::IA_GetBoolUsageBlock(struct XGRAPHICS::_IA_INTERNALCONST_BLOCK_HEADER *, struct XGRAPHICS::_IA_BOOLUSAGE_BLOCK **)
//{
//    mangled_ppc("?IA_GetBoolUsageBlock@XGRAPHICS@@YAIPAU_IA_INTERNALCONST_BLOCK_HEADER@1@PAPAU_IA_BOOLUSAGE_BLOCK@1@@Z");
//};

