/* ---------- headers */


/* ---------- constants */

/* ---------- definitions */

/* ---------- prototypes */

/* ---------- globals */

/* ---------- public code */

/* ---------- private code */

/* ---------- reverse engineering */

// struct XGRAPHICS::_CP_COMPILED_PROGRAM * XGRAPHICS::PS_AllocCP(struct XGRAPHICS::_PS_PROGRAM_STORE *, enum XGRAPHICS::_E_COMPILED_PROGRAM_TYPE);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::PS_DestroyCP(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// struct XGRAPHICS::_PS_INTERNAL_BLOCK * XGRAPHICS::PS_ProduceBlock(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_HASH_TABLE *, struct XGRAPHICS::_PS_EXTERNAL_BLOCK *);
// struct XGRAPHICS::_PS_PROGRAM_KEY * XGRAPHICS::PS_Store(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_CP_COMPILED_PROGRAM *);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::PS_RemoveBlock(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_HASH_TABLE *, struct XGRAPHICS::_PS_INTERNAL_BLOCK *, enum XGRAPHICS::_E_PS_BLOCK_TYPE);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::PS_Release(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_PROGRAM_KEY *);
// struct XGRAPHICS::_PS_PROGRAM_KEY * XGRAPHICS::PS_DuplicateKey(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_PROGRAM_KEY *);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::AllocVidMem(struct XGRAPHICS::_PS_PROGRAM_STORE *, unsigned int, struct XGRAPHICS::_SSM_VIDMEM *);
// void XGRAPHICS::UsePreAllocVidMem(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_OBJECT_LIST *, struct XGRAPHICS::_PS_INTERNAL_BLOCK *, enum XGRAPHICS::_E_PS_BLOCK_TYPE);
// void XGRAPHICS::ReuseVidMem(struct XGRAPHICS::_PS_INTERNAL_BLOCK *, struct XGRAPHICS::_OBJECT_LIST *, struct XGRAPHICS::_SSM_SSMOBJECT2CLIENT_INTERFACE *);
// void XGRAPHICS::AllocRSBlock(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_INTERNAL_BLOCK *, enum XGRAPHICS::_E_PS_BLOCK_TYPE, struct XGRAPHICS::_SSM_SSMOBJECT2CLIENT_INTERFACE *);
// enum XGRAPHICS::_E_PS_BLOCK_TYPE XGRAPHICS::operator++(enum XGRAPHICS::_E_PS_BLOCK_TYPE &);
// void XGRAPHICS::AllocShaderBlock(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_INTERNAL_BLOCK *, enum XGRAPHICS::_E_PS_BLOCK_TYPE, struct XGRAPHICS::_SSM_SSMOBJECT2CLIENT_INTERFACE *);
// enum XGRAPHICS::_E_PS_BLOCK_TYPE XGRAPHICS::operator++(enum XGRAPHICS::_E_PS_BLOCK_TYPE &, int);
// unsigned int XGRAPHICS::PS_ActivateProgKey(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_PROGRAM_KEY *, struct XGRAPHICS::_SSM_SSMOBJECT2CLIENT_INTERFACE *);
// void XGRAPHICS::PS_UpdateProgKeyTS(struct XGRAPHICS::_PS_PROGRAM_KEY *, unsigned __int64*);
// enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::PS_Destroy(struct XGRAPHICS::_PS_PROGRAM_STORE *);
// struct XGRAPHICS::_PS_PROGRAM_STORE * XGRAPHICS::PS_Create(void *, void * (*)(void *, unsigned int), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, void *), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, unsigned int, enum XGRAPHICS::_E_SSM_VIDMEMHEAP, struct XGRAPHICS::_SSM_VIDMEM *), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, struct XGRAPHICS::_SSM_VIDMEM *), struct XGRAPHICS::_TS_TEXTURE_SERVER *, struct XGRAPHICS::_SSM_REGISTRY *, struct XGRAPHICS::_ORDERED_LIST_FACTORY *, struct XGRAPHICS::_INTEGER_LIST_FACTORY *, struct XGRAPHICS::_OBJECT_LIST_FACTORY *, unsigned int, unsigned int const *);

//struct XGRAPHICS::_CP_COMPILED_PROGRAM * XGRAPHICS::PS_AllocCP(struct XGRAPHICS::_PS_PROGRAM_STORE *, enum XGRAPHICS::_E_COMPILED_PROGRAM_TYPE)
//{
//    mangled_ppc("?PS_AllocCP@XGRAPHICS@@YAPAU_CP_COMPILED_PROGRAM@1@PAU_PS_PROGRAM_STORE@1@W4_E_COMPILED_PROGRAM_TYPE@1@@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::PS_DestroyCP(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?PS_DestroyCP@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_PS_PROGRAM_STORE@1@PAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//struct XGRAPHICS::_PS_INTERNAL_BLOCK * XGRAPHICS::PS_ProduceBlock(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_HASH_TABLE *, struct XGRAPHICS::_PS_EXTERNAL_BLOCK *)
//{
//    mangled_ppc("?PS_ProduceBlock@XGRAPHICS@@YAPAU_PS_INTERNAL_BLOCK@1@PAU_PS_PROGRAM_STORE@1@PAU_HASH_TABLE@1@PAU_PS_EXTERNAL_BLOCK@1@@Z");
//};

//struct XGRAPHICS::_PS_PROGRAM_KEY * XGRAPHICS::PS_Store(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_CP_COMPILED_PROGRAM *)
//{
//    mangled_ppc("?PS_Store@XGRAPHICS@@YAPAU_PS_PROGRAM_KEY@1@PAU_PS_PROGRAM_STORE@1@PAU_CP_COMPILED_PROGRAM@1@@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::PS_RemoveBlock(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_HASH_TABLE *, struct XGRAPHICS::_PS_INTERNAL_BLOCK *, enum XGRAPHICS::_E_PS_BLOCK_TYPE)
//{
//    mangled_ppc("?PS_RemoveBlock@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_PS_PROGRAM_STORE@1@PAU_HASH_TABLE@1@PAU_PS_INTERNAL_BLOCK@1@W4_E_PS_BLOCK_TYPE@1@@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::PS_Release(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_PROGRAM_KEY *)
//{
//    mangled_ppc("?PS_Release@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_PS_PROGRAM_STORE@1@PAU_PS_PROGRAM_KEY@1@@Z");
//};

//struct XGRAPHICS::_PS_PROGRAM_KEY * XGRAPHICS::PS_DuplicateKey(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_PROGRAM_KEY *)
//{
//    mangled_ppc("?PS_DuplicateKey@XGRAPHICS@@YAPAU_PS_PROGRAM_KEY@1@PAU_PS_PROGRAM_STORE@1@PAU21@@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::AllocVidMem(struct XGRAPHICS::_PS_PROGRAM_STORE *, unsigned int, struct XGRAPHICS::_SSM_VIDMEM *)
//{
//    mangled_ppc("?AllocVidMem@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_PS_PROGRAM_STORE@1@IPAU_SSM_VIDMEM@1@@Z");
//};

//void XGRAPHICS::UsePreAllocVidMem(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_OBJECT_LIST *, struct XGRAPHICS::_PS_INTERNAL_BLOCK *, enum XGRAPHICS::_E_PS_BLOCK_TYPE)
//{
//    mangled_ppc("?UsePreAllocVidMem@XGRAPHICS@@YAXPAU_PS_PROGRAM_STORE@1@PAU_OBJECT_LIST@1@PAU_PS_INTERNAL_BLOCK@1@W4_E_PS_BLOCK_TYPE@1@@Z");
//};

//void XGRAPHICS::ReuseVidMem(struct XGRAPHICS::_PS_INTERNAL_BLOCK *, struct XGRAPHICS::_OBJECT_LIST *, struct XGRAPHICS::_SSM_SSMOBJECT2CLIENT_INTERFACE *)
//{
//    mangled_ppc("?ReuseVidMem@XGRAPHICS@@YAXPAU_PS_INTERNAL_BLOCK@1@PAU_OBJECT_LIST@1@PAU_SSM_SSMOBJECT2CLIENT_INTERFACE@1@@Z");
//};

//void XGRAPHICS::AllocRSBlock(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_INTERNAL_BLOCK *, enum XGRAPHICS::_E_PS_BLOCK_TYPE, struct XGRAPHICS::_SSM_SSMOBJECT2CLIENT_INTERFACE *)
//{
//    mangled_ppc("?AllocRSBlock@XGRAPHICS@@YAXPAU_PS_PROGRAM_STORE@1@PAU_PS_INTERNAL_BLOCK@1@W4_E_PS_BLOCK_TYPE@1@PAU_SSM_SSMOBJECT2CLIENT_INTERFACE@1@@Z");
//};

//enum XGRAPHICS::_E_PS_BLOCK_TYPE XGRAPHICS::operator++(enum XGRAPHICS::_E_PS_BLOCK_TYPE &)
//{
//    mangled_ppc("??EXGRAPHICS@@YA?AW4_E_PS_BLOCK_TYPE@0@AAW410@@Z");
//};

//void XGRAPHICS::AllocShaderBlock(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_INTERNAL_BLOCK *, enum XGRAPHICS::_E_PS_BLOCK_TYPE, struct XGRAPHICS::_SSM_SSMOBJECT2CLIENT_INTERFACE *)
//{
//    mangled_ppc("?AllocShaderBlock@XGRAPHICS@@YAXPAU_PS_PROGRAM_STORE@1@PAU_PS_INTERNAL_BLOCK@1@W4_E_PS_BLOCK_TYPE@1@PAU_SSM_SSMOBJECT2CLIENT_INTERFACE@1@@Z");
//};

//enum XGRAPHICS::_E_PS_BLOCK_TYPE XGRAPHICS::operator++(enum XGRAPHICS::_E_PS_BLOCK_TYPE &, int)
//{
//    mangled_ppc("??EXGRAPHICS@@YA?AW4_E_PS_BLOCK_TYPE@0@AAW410@H@Z");
//};

//unsigned int XGRAPHICS::PS_ActivateProgKey(struct XGRAPHICS::_PS_PROGRAM_STORE *, struct XGRAPHICS::_PS_PROGRAM_KEY *, struct XGRAPHICS::_SSM_SSMOBJECT2CLIENT_INTERFACE *)
//{
//    mangled_ppc("?PS_ActivateProgKey@XGRAPHICS@@YAIPAU_PS_PROGRAM_STORE@1@PAU_PS_PROGRAM_KEY@1@PAU_SSM_SSMOBJECT2CLIENT_INTERFACE@1@@Z");
//};

//void XGRAPHICS::PS_UpdateProgKeyTS(struct XGRAPHICS::_PS_PROGRAM_KEY *, unsigned __int64*)
//{
//    mangled_ppc("?PS_UpdateProgKeyTS@XGRAPHICS@@YAXPAU_PS_PROGRAM_KEY@1@PA_K@Z");
//};

//enum XGRAPHICS::_E_SSM_RETURNCODE XGRAPHICS::PS_Destroy(struct XGRAPHICS::_PS_PROGRAM_STORE *)
//{
//    mangled_ppc("?PS_Destroy@XGRAPHICS@@YA?AW4_E_SSM_RETURNCODE@1@PAU_PS_PROGRAM_STORE@1@@Z");
//};

//struct XGRAPHICS::_PS_PROGRAM_STORE * XGRAPHICS::PS_Create(void *, void * (*)(void *, unsigned int), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, void *), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, unsigned int, enum XGRAPHICS::_E_SSM_VIDMEMHEAP, struct XGRAPHICS::_SSM_VIDMEM *), enum XGRAPHICS::_E_SSM_RETURNCODE (*)(void *, struct XGRAPHICS::_SSM_VIDMEM *), struct XGRAPHICS::_TS_TEXTURE_SERVER *, struct XGRAPHICS::_SSM_REGISTRY *, struct XGRAPHICS::_ORDERED_LIST_FACTORY *, struct XGRAPHICS::_INTEGER_LIST_FACTORY *, struct XGRAPHICS::_OBJECT_LIST_FACTORY *, unsigned int, unsigned int const *)
//{
//    mangled_ppc("?PS_Create@XGRAPHICS@@YAPAU_PS_PROGRAM_STORE@1@PAXP6APAX0I@ZP6A?AW4_E_SSM_RETURNCODE@1@00@ZP6A?AW431@0IW4_E_SSM_VIDMEMHEAP@1@PAU_SSM_VIDMEM@1@@ZP6A?AW431@04@ZPAU_TS_TEXTURE_SERVER@1@PAU_SSM_REGISTRY@1@PAU_ORDERED_LIST_FACTORY@1@PAU_INTEGER_LIST_FACTORY@1@PAU_OBJECT_LIST_FACTORY@1@IPBI@Z");
//};

